# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def compute():
	ans = 0
	current_fibonacci_num = 1
	next_fibonacci_num = 2
	while current_fibonacci_num <= 4000000:
		if current_fibonacci_num % 2 == 0:
			ans += current_fibonacci_num
		current_fibonacci_num, next_fibonacci_num = next_fibonacci_num, current_fibonacci_num + next_fibonacci_num
	return str(ans)

if __name__ == "__main__":
	print(compute())
